from app.src.contracts.bwt.requests import (
    AccountType,
    CreateAccountRequest,
    CreateContactRequest,
    CreateDealRequest,
    DealLostReason,
    DealOrigin,
    DealStage,
    LoginRequest,
    PhonePayload,
    SetDealResponsibleRequest,
    UpdateDealStatusRequest,
)
from app.src.contracts.bwt.responses import (
    AccountContactResponse,
    AccountContactsResponse,
    AccountResponse,
    AccountsResponse,
    AddressContact,
    CompanyUserResponse,
    CompanyUsersResponse,
    ContactInfoResponse,
    CreateDealResponse,
    DealQueryResponse,
    DealsQueryResponse,
    LoginResponse,
    LoginUserResponse,
    PhoneContact,
    SimplifiedUserResponse,
    TokensResponse,
)

__all__ = [
    # Enums
    "AccountType",
    "DealOrigin",
    "DealStage",
    "DealLostReason",
    # Requests
    "LoginRequest",
    "PhonePayload",
    "CreateAccountRequest",
    "CreateContactRequest",
    "CreateDealRequest",
    "UpdateDealStatusRequest",
    "SetDealResponsibleRequest",
    # Responses
    "PhoneContact",
    "AddressContact",
    "TokensResponse",
    "LoginUserResponse",
    "LoginResponse",
    "CompanyUserResponse",
    "CompanyUsersResponse",
    "AccountResponse",
    "AccountsResponse",
    "AccountContactResponse",
    "AccountContactsResponse",
    "SimplifiedUserResponse",
    "ContactInfoResponse",
    "CreateDealResponse",
    "DealQueryResponse",
    "DealsQueryResponse",
]
